server:
  port: 7322

spring:
  application:
    name: 'p6e-coat-parent'
  config:
    import: D://env/p6e-coat-file-application.yml
logging:
  config: 'classpath:p6e-logback.xml'

club:
  p6e:
    auth:
      crossDomain:
        enabled: true
