server:
  port: 7322

spring:
  application:
    name: 'p6e-coat-parent'
  config:
    import: D://env/p6e-coat-file-application.yml
logging:
  config: 'classpath:p6e-logback.xml'

p6e:
  coat:
    common:
      cross-domain:
        enable: true
        white-list:
          - '*'
    auth:
      page:
        login: 'classpath:page/index.html'
        register: 'classpath:page/index.html'
        forgot-password: 'classpath:page/index.html'
